### ISSUE TITLE
装到openwrt路由并不行

### ISSUE THREAD

**Issue by JINLINBI** [chenhaowen01/gdut-drcom#1]
是不是因为那个自动跳转页面的服务器搞的?

**Comment by xnhw01** [comment]
你的路由器是？哪个平台的？

**Comment by JINLINBI** [comment]
tp-link 703r和tp-link 741rd试过,分别是barrier_xx和chaos_clamer

**Comment by JINLINBI** [comment]
你测试的路由是什么平台的?要不我刷成和你一样的试试?

**Comment by xnhw01** [comment]
到这个群来吧，群里有教程，279729674

**Comment by xnhw01** [comment]
注明一下你的github ID
