### ISSUE TITLE
ar71xx版本解压失败

### ISSUE THREAD

**Issue by MD-11F-RR** [chenhaowen01/gdut-drcom#3]
环境：NETGEAR WNDR3800 ，固件是明月的openwrt 14.07
进行的操作如下
直接右键另存为/release下的ar71xx.ipk
通过笔记本的shell命令：scp ar71xx.ipk root@192.168.1.10:/root
成功

再在链接路由器的shell里执行
opkg install ar71xx.ipk时提示

Collected errors:
- deb_extract: gdut-drcom_1.5-4a_ar71xx.ipk: invalid magic
- pkg_init_from_file: Failed to extract control file from gdut-drcom_1.5-4a_ar71xx.ipk.

同时用tar包尝试解压，也提示invalid magic

不知道是什么问题

**Comment by MD-11F-RR** [comment]
那个圆点是星号。本人尝试使用python版本的客户端，但是苦于ppp拨号不成功，应该是换行转义符没有正确发出。

成功在路由器上安装了python，但是pppoe拨号失败

**Comment by xnhw01** [comment]
tar 解压错误的，你先看一下文件有没有错误，md5校验如下：
440674ab2d480e248fdf334a075f35e5  gdut-drcom_1.5-4a_ar71xx.tar
c407d946d7ceb82cf0f4398ba467a792  gdut-drcom_1.5-4a_ar71xx.ipk

**Comment by MD-11F-RR** [comment]
测试过了，文件有问题。
我通过已经closed的一个issue找到了交流的Q群并通过Q群重新下载了文件，重下载的文件可以顺利的解压运行并认证校园网
