### ISSUE TITLE
Connection would be cut every 2 minutes

### ISSUE THREAD

**Issue by purerosefallen** [chenhaowen01/gdut-drcom#8]
I'm in LongDong campus, running this project on my computer with Ubuntu 18.04.3 LTS. 
From 1 pm today (9.19.2019), though the heartbeat process runs correctly, the PPPoE connection would be cut every 2 minutes.
I wonder if the official Dr.COM client is updated, in which the keep-alive flag changed. If so, I would be so glad if this client would be updated to match the latest version of Dr.COM client. Thanks!

**Comment by Frenqy** [comment]
most of people's network is OK with new flag '2f'
maybe you can change file

> gdut-drcom/src/gdut-drcom.conf

`keep_alive1_flag = 2a`
to
`keep_alive1_flag = 2f`
then compile yourself

**Comment by purerosefallen** [comment]
Thanks. I would try later.

**Comment by purerosefallen** [comment]
... `2a` is for the main campus. Which one is the correct one for Longdong campus?
