### ISSUE TITLE
Drcom更新了动态心跳包，大佬指导一下怎么破

### ISSUE THREAD

**Issue by Nick-Hopps** [chenhaowen01/gdut-drcom#9]

**Comment by purerosefallen** [comment]
What is the so-called *动态心跳包* ?

**Comment by Nick-Hopps** [comment]
> 
> 
> What is the so-called _动态心跳包_ ?

well, its just a conjecture of my friend and me, means that heartbeats change every time it sends verification. Actually I dont know exactly how it works now. By the way, if you're at leisure, maybe you can try something of it.

**Comment by Frenqy** [comment]
今天下午开始大部分都应该恢复了吧？如果不行就试试把pppoe_flag改为\x2f（似乎在这个项目里面应该是2f，还没细看）

**Comment by Nick-Hopps** [comment]
是的，目前已经恢复了，但是考虑到去年UA验证的尿性，估计过不久就会彻底换掉了

**Comment by Nick-Hopps** [comment]
还是要做好写新的代码的准备

**Comment by zhuzai123** [comment]
我也feel到了，细看了一下这项目的心跳函数似乎是以前5.2.1版本的，认证服务器昨天应该ban掉5.2.1版本的心跳包了，6.0.0版本心跳包正常，两版本心跳差别在于开启加密时kap1_2的checksum根据seed生成的方式不同，似乎不再是md5md4那四种了，可能可以反编译6.0.0尝试找找函数

**Comment by Frenqy** [comment]
今天在外面的时候看到了这个
[drcom-generic/issues/82](https://github.com/drcoms/drcom-generic/issues/82)
里面有一个不一样的py文件，本来想测试的，回来发现网络已经能用了。。
所以就先贴这了 有可能还会出问题，到时再翻出来看

**Comment by zhuzai123** [comment]
看了下 第二个包的8字节校验位生成原理都是一样的 猜测是现在的心跳代码有借鉴，只是包头修改了，楼上你说的是哪个py文件呢

**Comment by Frenqy** [comment]
@zhuzai123 
[在这里](https://github.com/drcoms/drcom-generic/issues/82#issuecomment-248691399)

**Comment by zhuzai123** [comment]
@MCsentic 应该是跟现在版本的心跳加密算法相同

**Comment by Nick-Hopps** [comment]
客户端更新了，坐等c版出来哈哈

**Comment by Frenqy** [comment]
今天更新过还是p版吧 看不出更新了什么

**Comment by ghost** [comment]
现在用单文件的版本，拨号会提示心跳DLL更新失败，然后连上大概一分钟就会自己断掉了。估计是验证过不了。

**Comment by Nick-Hopps** [comment]
我还是用的 1.6.8-3 版本的，现在好好的从来没掉过

**Comment by ghost** [comment]
> 我还是用的 1.6.8-3 版本的，现在好好的从来没掉过

Drcom-Dialer.哈哈 用的这个客户端，结果他似乎不能更新心跳包了。所以后面弄成在心跳包项目回复了，应该是我弄错了。
